Enhancing Job Listing with Filtering
SEGroup18/WolfJobs pull request #2
Opened 2024-10-29 00:35 UTC by MarthalaSaiKavya

Filter Implementation: Added a filtering system in JobsListView to allow users to filter job listings by type (all, full-time, part-time). This feature improves user navigation and helps applicants find relevant job opportunities more efficiently.

UI Improvements: Updated the styling of filter buttons for better visual distinction and user interaction. The selected filter button is highlighted to indicate the active filter.

Code Optimization: Utilized useMemo for efficient filtering, ensuring that the job list updates only when necessary, thus optimizing performance.

2024-10-31 00:26 UTC, AShivan26 requested changes
1.Need documentation in the Readme file
2.Create an Issue in Issue tab and Link it to the PR
3.I see testcases missing

2024-10-31 00:26 UTC, AShivan26 commented on frontend/src/components/Job/JobListView.tsx
> +  // Add other job properties as needed
remove the comments

2024-10-31 23:26 UTC, MarthalaSaiKavya commented on frontend/src/components/Job/JobListView.tsx
> +  // Add other job properties as needed
Sure, removed the comment

2024-10-31 23:27 UTC, MarthalaSaiKavya commented
Sure, fixed all of them that you suggested. Thank you for pointing out.

2024-10-31 23:29 UTC, MarthalaSaiKavya commented
Sure, made the fixes that you suggested. Thank you for pointing out.

2024-11-01 01:50 UTC, AShivan26 approved these changes

2024-11-01 01:50 UTC, merged